import { NestFactory } from '@nestjs/core';
import { AppModule } from '../src/app.module';
import { ValidationPipe } from '@nestjs/common';
import request from 'supertest';
import { PrismaService } from '../src/prisma/prisma.service';

async function testLiveGroqChat() {
  console.log('🚀 Starting NestJS app for real Groq API test...');
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));
  await app.listen(0);

  const prisma = app.get(PrismaService);
  const testEmail = 'real_groq_test_user@example.com';

  try {
    await prisma.user.deleteMany({ where: { email: testEmail } });

    // 1. Register User
    const regRes = await request(app.getHttpServer())
      .post('/auth/register')
      .send({
        name: 'Real Groq Tester',
        email: testEmail,
        password: 'Password123!',
      })
      .expect(201);

    const token = regRes.body.accessToken;
    console.log('✅ 1. User registered & JWT obtained');

    // 2. Fetch questions template
    const qRes = await request(app.getHttpServer())
      .get('/relationships/questions?relationshipType=Friendship')
      .set('Authorization', `Bearer ${token}`)
      .expect(200);

    const qId = qRes.body[0].id;
    const qText = qRes.body[0].questionText;

    // 3. Create relationship with questionnaire
    const relRes = await request(app.getHttpServer())
      .post('/relationships')
      .set('Authorization', `Bearer ${token}`)
      .send({
        name: 'Rahul',
        relationshipType: 'Friendship',
        category: 'Friends',
        photoUrl: null,
        answers: [
          {
            questionId: qId,
            questionText: qText,
            answer: 'Close and solid friendship.',
          },
        ],
      })
      .expect(201);

    const relId = relRes.body.id;
    console.log('✅ 2. Relationship created:', relId);

    // 4. Send chat message to trigger real Groq LLM response!
    console.log(
      '⏳ 3. Sending POST /chats/:relationshipId/messages to Groq...',
    );
    const chatRes = await request(app.getHttpServer())
      .post(`/chats/${relId}/messages`)
      .set('Authorization', `Bearer ${token}`)
      .send({ content: 'Rahul se thoda distance feel ho raha hai yaar.' })
      .expect(201);

    console.log('🎉 REAL GROQ AI RESPONSE RECEIVED:');
    console.log(JSON.stringify(chatRes.body, null, 2));

    if (
      chatRes.body.role === 'ASSISTANT' &&
      chatRes.body.content &&
      chatRes.body.content.length > 10
    ) {
      console.log('✅ 4. ASSISTANT response successfully generated by Groq!');
    } else {
      throw new Error('Groq response validation failed');
    }

    // 5. Verify database persistence
    const listRes = await request(app.getHttpServer())
      .get(`/chats/${relId}/messages`)
      .set('Authorization', `Bearer ${token}`)
      .expect(200);

    console.log('✅ 5. Persisted messages in PostgreSQL:', listRes.body.length);
    console.log(JSON.stringify(listRes.body, null, 2));

    await prisma.user.deleteMany({ where: { email: testEmail } });
    console.log('✨ ALL REAL GROQ VERIFICATION PASSED SUCCESSFULLY!');
  } finally {
    await app.close();
  }
}

testLiveGroqChat().catch((err) => {
  console.error('❌ Live Groq test failed:', err);
  process.exit(1);
});
